# Generated by Django 5.2.3 on 2025-06-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_moviepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="teampage",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teampage",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teampage",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teampage",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
    ]
