# Generated by Django 5.2.3 on 2025-07-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="home_page_images/"
            ),
        ),
    ]
