# Generated by Django 5.2.3 on 2025-07-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_homepage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularTvShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="popular_shows/")),
                ("youtube_link", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
