# Generated by Django 5.2.3 on 2025-07-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_populartvshow_delete_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("name", models.CharField(max_length=250)),
                ("year", models.IntegerField()),
                ("description", models.TextField()),
                ("is_carousel", models.BooleanField()),
                ("is_tvshow", models.BooleanField()),
                ("is_upcoming", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.movie"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PopularTvShow",
        ),
        migrations.AddField(
            model_name="genre",
            name="movie",
            field=models.ManyToManyField(to="core.movie"),
        ),
    ]
