# Generated by Django 5.2.3 on 2025-07-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_genre_movie_video_delete_populartvshow_genre_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
