# Generated by Django 5.2.3 on 2025-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_movie_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_trend",
            field=models.BooleanField(default=False),
        ),
    ]
