# Generated by Django 5.2.3 on 2025-07-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_movie_is_trend"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_background_image",
            field=models.BooleanField(default=False),
        ),
    ]
