# Generated by Django 5.2.3 on 2025-07-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_movie_is_background_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="is_background_image",
        ),
    ]
