# Generated by Django 5.2.3 on 2025-07-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_movie_is_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_background",
            field=models.BooleanField(default=False),
        ),
    ]
