# Generated by Django 5.2.3 on 2025-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_movie_is_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_series",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
