# Generated by Django 5.2.3 on 2025-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_movie_is_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="is_series",
            field=models.BooleanField(default=False),
        ),
    ]
