# Generated by Django 5.2.3 on 2025-07-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_movie_is_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_background2",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="movie",
            name="is_carousel",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="movie",
            name="is_tvshow",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="movie",
            name="is_upcoming",
            field=models.BooleanField(default=False),
        ),
    ]
