# Generated by Django 5.2.3 on 2025-07-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_movie_is_background2_alter_movie_is_carousel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="is_background2",
        ),
    ]
