# Generated by Django 5.2.3 on 2025-07-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_movie_is_background2"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_series_background",
            field=models.BooleanField(default=False),
        ),
    ]
