# Generated by Django 5.2.3 on 2025-07-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_movie_is_series_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_top_rated",
            field=models.BooleanField(default=False),
        ),
    ]
