# Generated by Django 5.2.3 on 2025-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_movie_is_top_rated"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_series_background1",
            field=models.BooleanField(default=False),
        ),
    ]
