# Generated by Django 5.2.3 on 2025-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_movie_is_series_background1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="is_series_background1",
        ),
        migrations.AddField(
            model_name="movie",
            name="is_film_background",
            field=models.BooleanField(default=False),
        ),
    ]
