# Generated by Django 5.2.3 on 2025-07-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_movie_is_series_background1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_film_rated_movie",
            field=models.BooleanField(default=False),
        ),
    ]
