# Generated by Django 5.2.3 on 2025-07-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_movie_is_film_rated_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="is_tvshow",
        ),
    ]
