# Generated by Django 5.2.3 on 2025-07-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_movie_is_tvshow"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
