# Generated by Django 5.2.3 on 2025-07-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_movie_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_trailer",
            field=models.BooleanField(default=False),
        ),
    ]
