# Generated by Django 5.2.3 on 2025-07-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_movie_is_trailer"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
