# Generated by Django 5.2.3 on 2025-07-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_movie_is_popular"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MoviePage",
        ),
        migrations.AddField(
            model_name="movie",
            name="is_movie_detailed",
            field=models.BooleanField(default=False),
        ),
    ]
