# Generated by Django 5.2.3 on 2025-07-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_delete_moviepage_movie_is_movie_detailed"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoviePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("year", models.IntegerField()),
                ("description", models.TextField(max_length=250)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("director", models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="is_movie_detailed",
        ),
    ]
