# Generated by Django 5.2.3 on 2025-07-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_moviepage_remove_movie_is_movie_detailed"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviepage",
            name="background_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
