# Generated by Django 5.2.3 on 2025-07-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_moviepage_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="movie",
            field=models.ManyToManyField(related_name="genres", to="core.movie"),
        ),
        migrations.AlterField(
            model_name="video",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="core.movie",
            ),
        ),
    ]
