# Generated by Django 5.2.3 on 2025-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_movie_slug_alter_genre_movie_alter_video_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="created_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
