# Generated by Django 5.2.3 on 2025-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_movie_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
