# Generated by Django 5.2.3 on 2025-07-14 15:18

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_movie_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="background_image_ppoi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5", editable=False, max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="background_image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to="movies/backgrounds/",
                verbose_name="Background Image",
            ),
        ),
    ]
