# Generated by Django 5.2.3 on 2025-07-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_castmember"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CastMember",
        ),
    ]
