# Generated by Django 5.2.3 on 2025-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_delete_castmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_web_series_background",
            field=models.BooleanField(default=False),
        ),
    ]
