# Generated by Django 5.2.3 on 2025-07-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_movie_is_web_series_background"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="is_web_series_background",
        ),
        migrations.AddField(
            model_name="movie",
            name="is_web_background",
            field=models.BooleanField(default=False),
        ),
    ]
