# Generated by Django 5.2.3 on 2025-07-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_movie_is_most_watch_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_rated_series",
            field=models.BooleanField(default=False),
        ),
    ]
