# Generated by Django 5.2.3 on 2025-07-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_movie_is_rated_series"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MoviePage",
        ),
    ]
