# Generated by Django 5.2.3 on 2025-07-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_contactform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="ContactForm",
        ),
    ]
