# Generated by Django 5.2.3 on 2025-07-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_contact_delete_contactform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
    ]
