# Generated by Django 5.2.3 on 2025-07-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_contact_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="featured_movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.movie",
            ),
        ),
    ]
