# Generated by Django 5.2.3 on 2025-07-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_contact_featured_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact_icon_svg",
            field=models.TextField(blank=True, verbose_name="Contact Icon SVG"),
        ),
        migrations.AddField(
            model_name="contact",
            name="map_iframe",
            field=models.TextField(blank=True, verbose_name="Google Map Embed Code"),
        ),
    ]
