# Generated by Django 5.2.3 on 2025-07-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_contact_contact_icon_svg_contact_map_iframe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="contact_icon_svg",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="featured_movie",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="map_iframe",
        ),
        migrations.CreateModel(
            name="ContactSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "map_iframe",
                    models.TextField(blank=True, verbose_name="Google Map Embed Code"),
                ),
                (
                    "contact_icon_svg",
                    models.TextField(blank=True, verbose_name="Contact Icon SVG"),
                ),
                (
                    "featured_movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.movie",
                    ),
                ),
            ],
        ),
    ]
