# Generated by Django 5.2.3 on 2025-07-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_remove_contact_contact_icon_svg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsettings",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Contact Email"
            ),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Phone Number"
            ),
        ),
    ]
