# Generated by Django 5.2.3 on 2025-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_contactsettings_address_contactsettings_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("author", models.CharField(default="Admin", max_length=100)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(blank=True, max_length=250)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text=",: drama,action", max_length=250
                    ),
                ),
                ("excerpt", models.TextField(blank=True, max_length=500)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
