# Generated by Django 5.2.3 on 2025-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_blogpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
    ]
