# Generated by Django 5.2.3 on 2025-07-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_category_tag_remove_blogpost_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="category",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.ManyToManyField(blank=True, to="core.category"),
        ),
    ]
