# Generated by Django 5.2.3 on 2025-07-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_remove_blogpost_category_blogpost_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
