# Generated by Django 5.2.3 on 2025-07-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_socialmedia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmedia",
            name="platform",
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="icon_class",
            field=models.CharField(default="fab fa-facebook-f", max_length=100),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="name",
            field=models.CharField(default="Facebook", max_length=50),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="url",
            field=models.URLField(default="https://example.com"),
            preserve_default=False,
        ),
    ]
