# Generated by Django 5.2.3 on 2025-07-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_remove_socialmedia_platform_socialmedia_icon_class_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("working_hours", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
