# Generated by Django 5.2.3 on 2025-07-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_contactinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="imdb_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="streamvibe_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
